name: Dim The Lights
favicon: null
layout_spectrum: 0.04989693150855601
typography_spectrum: 0.9669209045823663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5238028769381344
  lightness: 0.45598538871854544
  saturation: 0.23923368752002716
  rhythmicContrast: 0.5275001199916005
purpose: []
